### ISSUE TITLE
Linux pip sees version 0.0.2 only

### ISSUE THREAD

**Issue by memowe** [tennom/saxonpy#3]
Hi there, thank you so much for your effort! :)

I have problems installing the latest version ([pypi.org lists 0.0.3 as the latest version](https://pypi.org/project/saxonpy/0.0.3/)) via pip on Ubuntu 20.04:

```bash
memowe@comP1ter:/tmp$ python3 -m venv env
memowe@comP1ter:/tmp$ source env/bin/activate

(env) memowe@comP1ter:/tmp$ python --version
Python 3.8.10
(env) memowe@comP1ter:/tmp$ pip --version
pip 20.0.2 from /tmp/env/lib/python3.8/site-packages/pip (python 3.8)

(env) memowe@comP1ter:/tmp$ pip install saxonpy==0.0.3
ERROR: Could not find a version that satisfies the requirement saxonpy==0.0.3 (from versions: 0.0.2)
ERROR: No matching distribution found for saxonpy==0.0.3

(env) memowe@comP1ter:/tmp$ pip install saxonpy
Collecting saxonpy
  Using cached saxonpy-0.0.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (48.1 MB)
Installing collected packages: saxonpy
Successfully installed saxonpy-0.0.2
```

Anything I can do to find the latest version?

**Comment by memowe** [comment]
Ah, I see. There are download files for Windows and Mac only: https://pypi.org/project/saxonpy/0.0.3/#files

Are there plans to support linux in the near future?

**Comment by tennom** [comment]
Hi Mirko, Thanks for the feedback. I mislabeled "0.02" for Linux, I'm sorry. They are exactly the same program. I initially had it for linux only and later on added support for Mac and Windows.
 I labeled a different version tag because Pypi server somehow didn't let me reuse the old version to upload the modules for different OS platforms, so I just went with the "0.03":)
I'm also planning to update the modules to the latest Saxonica tools soon.
________________________________

**Comment by memowe** [comment]
Hey Tennom, sounds great! Thank you for explaining, I'll work happily with 0.0.2 then. :)
